# Generated by Django 2.1.3 on 2018-11-15 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractAdministrativeSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrative_fee', models.DecimalField(decimal_places=2, default=0, max_digits=64)),
                ('administrative_fee_tax', models.DecimalField(decimal_places=2, default=0, max_digits=64)),
                ('administrative_fee_base', models.DecimalField(decimal_places=2, default=0, max_digits=64)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentNotification',
            fields=[
                ('abstractadministrativesegment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payulatam.AbstractAdministrativeSegment')),
                ('bank_id', models.CharField(max_length=255)),
                ('bank_referenced_name', models.CharField(max_length=100)),
                ('error_code_bank', models.CharField(max_length=255)),
                ('error_message_bank', models.CharField(max_length=255)),
                ('billing_address', models.TextField()),
                ('billing_city', models.CharField(max_length=255)),
                ('billing_country', models.CharField(choices=[('ARGENTINA', 'AR'), ('BRAZIL', 'BR'), ('COLOMBIA', 'CO'), ('MEXICO', 'MX'), ('PANAMA', 'PA'), ('PERU', 'PE'), ('CHILE', 'CL')], max_length=2)),
                ('pse_bank', models.CharField(max_length=255)),
                ('pse_reference1', models.CharField(max_length=255)),
                ('pse_reference3', models.CharField(max_length=255)),
                ('pse_reference2', models.CharField(max_length=255)),
                ('shipping_address', models.CharField(max_length=50)),
                ('shipping_city', models.CharField(max_length=50)),
                ('shipping_country', models.CharField(choices=[('ARGENTINA', 'AR'), ('BRAZIL', 'BR'), ('COLOMBIA', 'CO'), ('MEXICO', 'MX'), ('PANAMA', 'PA'), ('PERU', 'PE'), ('CHILE', 'CL')], max_length=2)),
                ('transaction_id', models.CharField(db_index=True, max_length=36)),
                ('transaction_date', models.DateTimeField()),
                ('transaction_bank_id', models.CharField(max_length=255)),
                ('payment_method', models.IntegerField()),
                ('payment_method_id', models.IntegerField()),
                ('payment_method_type', models.IntegerField()),
                ('payment_method_name', models.CharField(max_length=255)),
                ('payment_request_state', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('reference_sale', models.CharField(max_length=255)),
                ('risk', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=64, null=True)),
                ('sign', models.CharField(max_length=255)),
                ('email_buyer', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('office_phone', models.CharField(max_length=20)),
                ('merchant_id', models.IntegerField()),
                ('customer_number', models.IntegerField()),
                ('nickname_seller', models.CharField(max_length=150)),
                ('nickname_buyer', models.CharField(max_length=150)),
                ('antifraud_merchant_id', models.CharField(max_length=100)),
                ('airline_code', models.CharField(max_length=4)),
                ('cus', models.CharField(max_length=64)),
                ('authorization_code', models.CharField(max_length=12)),
                ('extra1', models.CharField(max_length=255)),
                ('extra2', models.CharField(max_length=255)),
                ('extra3', models.CharField(max_length=255)),
                ('attempts', models.IntegerField()),
                ('ip', models.CharField(max_length=39)),
                ('date', models.DateTimeField()),
                ('test', models.BooleanField()),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payu_payment_notification',
            },
            bases=('payulatam.abstractadministrativesegment', models.Model),
        ),
    ]
