# Generated by Django 2.1.3 on 2018-11-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=36)),
                ('transaction_date', models.DateTimeField()),
                ('reference_sale', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('payment_method', models.IntegerField()),
                ('payment_method_id', models.IntegerField()),
                ('payment_method_type', models.IntegerField()),
                ('payment_method_name', models.CharField(max_length=255)),
                ('payment_request_state', models.CharField(max_length=32)),
                ('cc_number', models.CharField(max_length=100)),
                ('cc_holder', models.CharField(max_length=100)),
                ('franchise', models.CharField(max_length=100)),
                ('installments_number', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=64)),
                ('additional_value', models.DecimalField(decimal_places=2, max_digits=64)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=64)),
                ('administrative_fee', models.DecimalField(decimal_places=2, max_digits=64)),
                ('administrative_fee_tax', models.DecimalField(decimal_places=2, max_digits=64)),
                ('administrative_fee_base', models.DecimalField(decimal_places=2, max_digits=64)),
                ('exchange_rate', models.DecimalField(decimal_places=2, max_digits=64)),
                ('currency', models.CharField(max_length=3)),
                ('risk', models.DecimalField(decimal_places=2, max_digits=64)),
                ('sign', models.CharField(max_length=255)),
                ('response_code_pol', models.CharField(max_length=255)),
                ('response_message_pol', models.CharField(max_length=255)),
                ('state_pol', models.CharField(max_length=32)),
                ('reference_pol', models.CharField(max_length=255)),
                ('commision_pol', models.DecimalField(decimal_places=2, max_digits=64)),
                ('commision_pol_currency', models.CharField(max_length=3)),
                ('billing_address', models.CharField(max_length=255)),
                ('billing_city', models.CharField(max_length=255)),
                ('billing_country', models.CharField(max_length=2)),
                ('shipping_address', models.CharField(max_length=50)),
                ('shipping_city', models.CharField(max_length=50)),
                ('shipping_country', models.CharField(max_length=2)),
                ('email_buyer', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('office_phone', models.CharField(max_length=20)),
                ('merchant_id', models.IntegerField()),
                ('customer_number', models.IntegerField()),
                ('nickname_seller', models.CharField(max_length=150)),
                ('nickname_buyer', models.CharField(max_length=150)),
                ('bank_id', models.CharField(max_length=255)),
                ('bank_referenced_name', models.CharField(max_length=100)),
                ('transaction_bank_id', models.CharField(max_length=255)),
                ('error_code_bank', models.CharField(max_length=255)),
                ('error_message_bank', models.CharField(max_length=255)),
                ('antifraud_merchant_id', models.CharField(max_length=100)),
                ('airline_code', models.CharField(max_length=4)),
                ('cus', models.CharField(max_length=64)),
                ('authorization_code', models.CharField(max_length=12)),
                ('extra1', models.CharField(max_length=255)),
                ('extra2', models.CharField(max_length=255)),
                ('extra3', models.CharField(max_length=255)),
                ('pse_bank', models.CharField(max_length=255)),
                ('pse_reference1', models.CharField(max_length=255)),
                ('pse_reference3', models.CharField(max_length=255)),
                ('pse_reference2', models.CharField(max_length=255)),
                ('attempts', models.IntegerField()),
                ('ip', models.CharField(max_length=39)),
                ('date', models.DateTimeField()),
                ('test', models.BooleanField()),
                ('flag', models.BooleanField()),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payu_payment_notification',
            },
        ),
    ]
