# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-30 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrative_fee', models.DecimalField(decimal_places=2, default=0, max_digits=64)),
                ('administrative_fee_tax', models.DecimalField(decimal_places=2, default=0, max_digits=64)),
                ('administrative_fee_base', models.DecimalField(decimal_places=2, default=0, max_digits=64)),
                ('bank_id', models.CharField(max_length=255)),
                ('bank_referenced_name', models.CharField(max_length=100)),
                ('error_code_bank', models.CharField(max_length=255)),
                ('error_message_bank', models.CharField(max_length=255)),
                ('billing_address', models.TextField()),
                ('billing_city', models.CharField(max_length=255)),
                ('billing_country', models.CharField(max_length=2)),
                ('cc_number', models.CharField(max_length=100)),
                ('cc_holder', models.CharField(max_length=100)),
                ('franchise', models.CharField(max_length=100)),
                ('installments_number', models.IntegerField()),
                ('response_code_pol', models.CharField(max_length=255)),
                ('response_message_pol', models.CharField(max_length=255)),
                ('state_pol', models.CharField(max_length=32)),
                ('reference_pol', models.CharField(max_length=255)),
                ('commision_pol', models.DecimalField(decimal_places=2, default=0, max_digits=64)),
                ('commision_pol_currency', models.CharField(max_length=3)),
                ('cus', models.CharField(max_length=64)),
                ('pse_bank', models.CharField(max_length=255)),
                ('pse_reference1', models.CharField(max_length=255)),
                ('pse_reference3', models.CharField(max_length=255)),
                ('pse_reference2', models.CharField(max_length=255)),
                ('shipping_address', models.TextField()),
                ('shipping_city', models.CharField(max_length=255)),
                ('shipping_country', models.CharField(max_length=2)),
                ('transaction_id', models.CharField(db_index=True, max_length=36)),
                ('transaction_date', models.DateTimeField()),
                ('transaction_bank_id', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=64)),
                ('additional_value', models.DecimalField(decimal_places=2, default=0, max_digits=64)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=64)),
                ('exchange_rate', models.DecimalField(decimal_places=2, default=0, max_digits=64)),
                ('currency', models.CharField(choices=[('ARS', 'ARS'), ('BRL', 'BRL'), ('COP', 'COP'), ('MXN', 'MXN'), ('USD', 'USD'), ('PEN', 'PEN'), ('CLP', 'CLP')], max_length=3)),
                ('flag', models.BooleanField(default=False)),
                ('flag_code', models.CharField(choices=[('1001', 'Duplicate Transaction'), ('1002', 'Invalid Sign')], max_length=4)),
                ('flag_info', models.CharField(max_length=100)),
                ('payment_method', models.IntegerField()),
                ('payment_method_id', models.IntegerField()),
                ('payment_method_type', models.IntegerField()),
                ('payment_method_name', models.CharField(max_length=255)),
                ('payment_request_state', models.CharField(max_length=32)),
                ('reference_sale', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('risk', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=64, null=True)),
                ('sign', models.CharField(max_length=255)),
                ('email_buyer', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('office_phone', models.CharField(max_length=20)),
                ('merchant_id', models.IntegerField()),
                ('customer_number', models.IntegerField(blank=True, null=True)),
                ('nickname_seller', models.CharField(max_length=150)),
                ('nickname_buyer', models.CharField(max_length=150)),
                ('antifraud_merchant_id', models.CharField(max_length=100)),
                ('airline_code', models.CharField(max_length=4)),
                ('authorization_code', models.CharField(max_length=12)),
                ('extra1', models.CharField(max_length=255)),
                ('extra2', models.CharField(max_length=255)),
                ('extra3', models.CharField(max_length=255)),
                ('attempts', models.IntegerField()),
                ('ip', models.CharField(max_length=39)),
                ('date', models.DateTimeField()),
                ('test', models.BooleanField()),
                ('raw', models.TextField()),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payu_payment_notification',
            },
        ),
    ]
