# Generated by Django 2.1.3 on 2018-11-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payulatam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentnotification',
            name='customer_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
