# Generated by Django 2.1.3 on 2018-11-12 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentnotification',
            name='additional_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=64),
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='administrative_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=64),
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='administrative_fee_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=64),
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='administrative_fee_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=64),
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='commision_pol',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=64),
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=64),
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='risk',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=64, null=True),
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=64),
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=64),
        ),
    ]
